export const LANDING_PAGE_PRIORITY = new Map<string, number>([
  ["home", -30],
  ["intro", -20],
  ["introduction", -10],
  ["landingPage", -5],
]);

export const TOPIC_LESSON_ORDER: Record<string, string[]> = {
  "complex-physics": [
    "statisticalMechanics",
    "metropolisAlgorithm",
    "phaseTransitions",
    "meanFieldResults",
    "transferMatrix",
    "criticalPhenomena",
    "percolation",
    "fractals",
    "selfOrganizedCriticality",
    "Networks",
    "agentbased",
    "econophysics",
  ],
  "advanced-deep-learning": [
    "ann",
    "design-and-optimization",
    "cnn",
    "gan",
    "vae",
    "unet",
    "transformers",
    "analysis-and-theory",
  ],
  "applied-machine-learning": [
    "loss-optimization",
    "trees-ensembles",
    "dimensionality-reduction",
    "neural-networks-fundamentals",
    "graph-neural-networks",
    "recurrent-neural-networks",
    "generative-adversarial-networks",
  ],
  "applied-statistics": [
    "introduction-concepts",
    "probability-density-functions",
    "error-propagation",
    "simulation-fitting",
    "chi-square-method",
    "hypothesis-testing",
    "design-of-experiments",
    "anova",
    "random-effects",
    "longitudinal-data",
    "bayesian-statistics",
    "advanced-fitting-calibration",
    "machine-learning-data-analysis",
  ],
  "continuum-mechanics": [
    "contapprox",
    "tensorfundamentals",
    "stressandstrain",
    "elasticity",
    "dynamics",
    "fluids",
    "fluidsinmotion",
    "viscousflow",
    "creepingflow",
    "channelsandpipes",
    "gravitywaves",
    "weakstokes",
    "fem",
    "pythonpackages",
    "examdisp",
  ],
  "dynamical-models": [
    "differential-equations",
    "transcription-translation",
    "mutational-analysis",
    "gene-expression-noise",
    "transcriptional-regulation",
    "feedback-loops",
    "signal-transduction",
    "gene-regulatory-networks",
    "bacterial-growth",
  ],
  "inverse-problems": [
    "regularization",
    "bayesian-inversion",
    "tikhonov",
    "linear-tomography",
    "monte-carlo-methods",
    "geophysical-inversion",
    "information-entropy",
  ],
  "online-reinforcement-learning": [
    "regret",
    "feedback-and-settings",
    "ftl-and-hedge",
    "bandits-ucb-exp3",
    "contextual-bandits-exp4",
    "mdp-and-dp",
    "monte-carlo-rl",
    "td-sarsa-qlearning",
    "deep-rl-dqn",
    "average-reward-online-rl",
  ],
  "quantum-optics": [
    "quantization-single-mode",
    "quantum-fluctuations",
    "vacuum-fluctuations",
    "coherent-states",
    "phase-space-representations",
    "coherence-functions",
    "higher-order-coherence",
    "interferometry",
    "squeezed-states",
    "atom-field-interaction",
    "jaynes-cummings",
    "cavity-qed",
    "quantum-measurements",
  ],
  "scientific-computing": [
    "bounding-errors",
    "linear-equations",
    "linear-least-squares",
    "eigen-systems",
    "nonlinear-equations",
    "nonlinear-systems",
    "optimization",
    "fft",
    "initial-value-problems",
    "partial-differential-equations",
  ],
};

export const LESSON_SUMMARIES: Record<string, Record<string, string>> = {
  "complex-physics": {
    statisticalMechanics: "Boltzmann distribution, partition functions, and ensemble averages",
    metropolisAlgorithm: "Monte Carlo sampling using the Metropolis-Hastings method",
    phaseTransitions: "Critical behavior and order parameters in phase transitions",
    meanFieldResults: "Mean field approximations for interacting many-body systems",
    transferMatrix: "Exact solutions using transfer matrix techniques",
    criticalPhenomena: "Universality, scaling laws, and renormalization",
    percolation: "Percolation thresholds, critical exponents, and Bethe lattice theory",
    fractals: "Fractal dimension, the Mandelbrot set, and box-counting methods",
    selfOrganizedCriticality: "Sandpile models and power-law distributions",
    Networks: "Graph theory, small-world networks, and scale-free topology",
    agentbased: "Simulating emergent behavior from individual agent rules",
    econophysics: "Statistical physics methods applied to financial markets",
  },
  "advanced-deep-learning": {
    ann: "Feedforward networks, backpropagation, and activation functions",
    cnn: "Convolutional layers, pooling, and image feature extraction",
    "design-and-optimization": "Architecture design choices and hyperparameter tuning",
    vae: "Variational autoencoders for probabilistic latent representations",
    gan: "Generator-discriminator training for realistic data synthesis",
    unet: "Encoder-decoder architecture for image segmentation",
    transformers: "Self-attention mechanisms and sequence modeling",
    "analysis-and-theory": "Theoretical analysis of deep learning convergence and generalization",
  },
  "applied-machine-learning": {
    "loss-optimization": "Gradient descent variants and loss function design",
    "trees-ensembles": "Decision trees, random forests, and boosting methods",
    "dimensionality-reduction": "PCA, t-SNE, and manifold learning techniques",
    "neural-networks-fundamentals": "Basic neural network architectures and training",
    "recurrent-neural-networks": "Extension: Sequential data modeling with RNNs and LSTMs",
    "graph-neural-networks": "Message passing and learning on graph-structured data",
    "generative-adversarial-networks": "Extension: GAN architectures for generative modeling",
  },
  "applied-statistics": {
    "introduction-concepts": "Core statistical concepts: mean, variance, and distributions",
    "probability-density-functions": "Continuous and discrete probability distributions",
    "error-propagation": "Uncertainty quantification through error propagation rules",
    "simulation-fitting": "Monte Carlo simulation and curve fitting methods",
    "chi-square-method": "Goodness-of-fit testing and chi-square statistics",
    "hypothesis-testing": "Null hypothesis significance testing and p-values",
    anova: "Analysis of variance for comparing group means",
    "design-of-experiments": "Experimental design principles and factorial designs",
    "random-effects": "Mixed models with random and fixed effects",
    "longitudinal-data": "Repeated measures and time-series analysis methods",
    "bayesian-statistics": "Prior distributions, posterior inference, and Bayes' theorem",
    "advanced-fitting-calibration": "Advanced model calibration and nonlinear fitting",
    "machine-learning-data-analysis": "ML techniques for statistical data analysis",
  },
  "continuum-mechanics": {
    contapprox: "The continuum approximation and material descriptions",
    tensorfundamentals: "Tensor algebra, notation, and coordinate transformations",
    stressandstrain: "Stress tensors, strain measures, and constitutive laws",
    elasticity: "Linear elasticity theory and elastic wave propagation",
    dynamics: "Conservation laws and equations of motion for continua",
    fluids: "Fluid statics, pressure, and buoyancy principles",
    fluidsinmotion: "Euler and Navier-Stokes equations for fluid flow",
    viscousflow: "Viscous effects, boundary layers, and Reynolds number",
    creepingflow: "Low Reynolds number Stokes flow solutions",
    channelsandpipes: "Poiseuille flow and flow in channels and pipes",
    gravitywaves: "Surface gravity waves and dispersion relations",
    weakstokes: "Weak formulation of Stokes equations",
    fem: "Finite element method for continuum problems",
    pythonpackages: "Python tools for continuum mechanics simulations",
    examdisp: "Course review — every big idea retold as detective stories",
  },
  "dynamical-models": {
    "differential-equations": "The bathtub equation: how production and degradation set every steady state in biology",
    "transcription-translation": "Coupled ODEs for mRNA and protein — two timescales, one elegant system",
    "mutational-analysis": "DNA proofreading, jackpot cultures, and the statistics of rare events",
    "gene-expression-noise": "Why genetically identical cells behave differently — intrinsic and extrinsic noise",
    "transcriptional-regulation": "The Hill function: how cooperative binding turns a gentle slope into a sharp switch",
    "feedback-loops": "Switches, oscillators, and memory — what feedback loops can do",
    "signal-transduction": "How cells read their mail: chemotaxis, adaptation, and lateral inhibition",
    "gene-regulatory-networks": "The Lego bricks of gene regulation — motifs nature uses over and over",
    "bacterial-growth": "Resource allocation, ribosome regulation, and how a cell turns physics into life",
  },
  "inverse-problems": {
    regularization: "The L-curve, Tikhonov penalty, and the art of balancing data fit against model simplicity",
    "bayesian-inversion": "Regularization is a prior in disguise — the probabilistic viewpoint that unifies everything",
    tikhonov: "Steepest descent, conjugate gradients, and iterative tricks for million-parameter problems",
    "linear-tomography": "From seismic rays to Earth images — a complete tomographic inversion workflow",
    "monte-carlo-methods": "MCMC sampling — exploring the full posterior when formulas fail",
    "geophysical-inversion": "Fault and glacier case studies where the answer is always a distribution",
    "information-entropy": "Shannon entropy and KL divergence — measuring what the data actually taught you",
  },
  "online-reinforcement-learning": {
    regret: "Regret bounds and online learning performance metrics",
    "feedback-and-settings": "Feedback models: full information vs. bandit",
    "ftl-and-hedge": "Follow the Leader, Hedge, and expert algorithms",
    "bandits-ucb-exp3": "UCB and EXP3 algorithms for bandit problems",
    "contextual-bandits-exp4": "Contextual bandits and the EXP4 algorithm",
    "mdp-and-dp": "Markov decision processes and dynamic programming",
    "monte-carlo-rl": "Monte Carlo methods for policy evaluation",
    "td-sarsa-qlearning": "Temporal difference, SARSA, and Q-learning",
    "deep-rl-dqn": "Deep Q-networks and neural function approximation",
    "average-reward-online-rl": "Average reward criteria for continuing tasks",
  },
  "quantum-optics": {
    "quantization-single-mode": "Canonical quantization of a single electromagnetic mode",
    "quantum-fluctuations": "Vacuum fluctuations, zero-point energy, and quadrature operators",
    "vacuum-fluctuations": "Multimode fields, thermal states, Casimir effect, and vacuum energy consequences",
    "coherent-states": "Coherent states: definition, photon statistics, displacement operator, and algebraic properties",
    "phase-space-representations": "Q, P, and Wigner quasi-probability distributions for visualizing quantum light",
    "coherence-functions": "First-order correlation and optical coherence",
    "higher-order-coherence": "Photon bunching, antibunching, and g(2) functions",
    interferometry: "Single-photon experiments, beam splitters, HOM effect, and quantum-enhanced interferometry",
    "squeezed-states": "Quadrature squeezing, displaced squeezed states, and two-mode entanglement",
    "atom-field-interaction": "Dipole coupling and the rotating wave approximation",
    "jaynes-cummings": "Jaynes-Cummings model, Rabi oscillations, and collapse-revival dynamics",
    "cavity-qed": "Strong coupling regime in optical cavities",
    "quantum-measurements": "Measurement theory, POVMs, and quantum state tomography",
  },
  "scientific-computing": {
    "bounding-errors": "Floating-point arithmetic and error analysis",
    "linear-equations": "Gaussian elimination and LU factorization",
    "linear-least-squares": "QR factorization and least squares data fitting",
    "nonlinear-equations": "Root finding: bisection, Newton, and secant methods",
    "nonlinear-systems": "Newton's method for systems of nonlinear equations",
    optimization: "BFGS, conjugate gradients, and metaheuristic optimization",
    "eigen-systems": "Power method, Rayleigh quotient iteration, QR algorithm, and Gershgorin bounds",
    fft: "Fast Fourier Transform and spectral analysis",
    "initial-value-problems": "Runge-Kutta and multistep ODE integration methods",
    "partial-differential-equations": "Finite difference and spectral methods for PDEs",
  },
};

export function getLessonSummary(topicId: string, slug: string): string | undefined {
  return LESSON_SUMMARIES[topicId]?.[slug];
}

export function isLandingPage(slug: string): boolean {
  return LANDING_PAGE_PRIORITY.has(slug);
}

export interface SearchableLesson {
  slug: string;
  title: string;
  summary?: string;
  searchableText: string;
}
