'use client';

import React from 'react';
import { GameOfLife } from './complex-physics/GameOfLife';
import { LorenzAttractor } from './complex-physics/LorenzAttractor';
import { MandelbrotFractal } from './complex-physics/MandelbrotFractal';
import { IsingModel } from './complex-physics/IsingModel';
import { PercolationSim } from './complex-physics/PercolationSim';
import { BakSneppen } from './complex-physics/BakSneppen';
import { BetHedging } from './complex-physics/BetHedging';
import { HurstExponent } from './complex-physics/HurstExponent';
import { ScaleFreeNetwork } from './complex-physics/ScaleFreeNetwork';
import { PhaseTransitionIsing1D } from './complex-physics/PhaseTransitionIsing1D';
import { BetheLatticePercolation } from './complex-physics/BetheLatticePercolation';
import { FractalDimension } from './complex-physics/FractalDimension';
import { RandomWalkFirstReturn } from './complex-physics/RandomWalkFirstReturn';
import { SandpileModel } from './complex-physics/SandpileModel';
import { StockVariance } from './complex-physics/StockVariance';
import type { SimulationComponentProps } from '@/shared/types/simulation';


// ============ SIMULATION REGISTRY ============

export const COMPLEX_SIMULATIONS: Record<string, React.ComponentType<SimulationComponentProps>> = {
  'game-of-life': GameOfLife,
  'lorenz-attractor': LorenzAttractor,
  'mandelbrot-fractal': MandelbrotFractal,
  'ising-model': IsingModel,
  'percolation': PercolationSim,
  'bak-sneppen': BakSneppen,
  'bet-hedging': BetHedging,
  'hurst-exponent': HurstExponent,
  'scale-free-network': ScaleFreeNetwork,
  'phase-transition-ising-1d': PhaseTransitionIsing1D,
  'bethe-lattice': BetheLatticePercolation,
  'fractal-dimension': FractalDimension,
  'random-walk-first-return': RandomWalkFirstReturn,
  'sandpile-model': SandpileModel,
  'stock-variance': StockVariance,
};

// ============ CO-LOCATED DESCRIPTIONS ============

export const COMPLEX_DESCRIPTIONS: Record<string, string> = {
  "game-of-life": "Conway's Game of Life — a cellular automaton where cells evolve based on neighbor counts, producing emergent complexity from simple rules.",
  "lorenz-attractor": "The Lorenz attractor — a chaotic dynamical system exhibiting sensitive dependence on initial conditions (the butterfly effect).",
  "mandelbrot-fractal": "The Mandelbrot set — an infinitely detailed fractal generated by iterating z = z² + c in the complex plane.",
  "ising-model": "The 2D Ising model — a lattice of interacting spins that undergoes a phase transition between ordered and disordered states.",
  "percolation": "Site percolation on a lattice — demonstrates the critical threshold at which a connected cluster spans the system.",
  "bak-sneppen": "The Bak–Sneppen model — a minimal model of self-organized criticality where the least-fit species co-evolves with its neighbors.",
  "bet-hedging": "Bet-hedging strategies — comparing deterministic vs. stochastic survival strategies in fluctuating environments.",
  "hurst-exponent": "Hurst exponent estimation — measuring long-range dependence in time series using rescaled range analysis.",
  "scale-free-network": "Scale-free network growth — Barabási–Albert preferential attachment producing power-law degree distributions.",
  "phase-transition-ising-1d": "1D Ising model — exploring why one-dimensional systems lack a finite-temperature phase transition.",
  "bethe-lattice": "Bethe lattice percolation — exact percolation threshold calculation on a tree-like lattice structure.",
  "fractal-dimension": "Fractal dimension estimation — computing the box-counting dimension of self-similar geometric objects.",
  "random-walk-first-return": "Random walk first-return times — the distribution of steps before a 1D random walker returns to the origin.",
  "sandpile-model": "The Abelian sandpile model — grains topple when a cell exceeds a threshold, producing power-law avalanche distributions.",
  "stock-variance": "Stock return variance analysis — examining how financial return distributions deviate from Gaussian behavior.",
};

export const COMPLEX_FIGURES: Record<string, { src: string; caption: string }> = {
  'complex-percolation-video': {
    src: 'https://archive.org/download/percolation-2d-simulation/percolation-2d-simulation.mp4',
    caption: 'Percolation evolution animation for cluster formation and critical threshold intuition.',
  },
  'complex-sandpile-image': {
    src: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Sandpile_model.gif',
    caption: 'Self-organized criticality in sandpile avalanches.',
  },
};
